// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Hugues Codeur",
            "email": "huguescodeur@gmail.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authentifie un utilisateur (email ou username) et retourne le token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Connexion",
                "parameters": [
                    {
                        "description": "Identifiants de connexion",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Format JSON invalide ou validation échouée",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Identifiants incorrects",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Crée un compte et retourne le token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Inscription d'un nouvel utilisateur",
                "parameters": [
                    {
                        "description": "Données d'inscription",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Format JSON invalide ou validation échouée",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/comments/{commentID}/likes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne tous les likes d'un commentaire",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment Likes"
                ],
                "summary": "Likes d'un commentaire",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du commentaire",
                        "name": "commentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/commentlike.CommentLike"
                            }
                        }
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ajoute une réaction (like/love/laugh) à un commentaire",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment Likes"
                ],
                "summary": "Liker un commentaire",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du commentaire",
                        "name": "commentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Type de réaction",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commentlike.reactionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/commentlike.CommentLike"
                        }
                    },
                    "400": {
                        "description": "Type de réaction invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Déjà liké",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retire la réaction de l'utilisateur connecté sur un commentaire",
                "tags": [
                    "Comment Likes"
                ],
                "summary": "Supprimer un like sur un commentaire",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du commentaire",
                        "name": "commentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Like supprimé"
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Like non trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change le type de réaction de l'utilisateur connecté sur un commentaire",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment Likes"
                ],
                "summary": "Modifier une réaction sur un commentaire",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du commentaire",
                        "name": "commentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouvelle réaction",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/commentlike.reactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/commentlike.CommentLike"
                        }
                    },
                    "400": {
                        "description": "Type invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Like non trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/comments/{commentID}/likes/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne le like de l'utilisateur connecté sur un commentaire",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comment Likes"
                ],
                "summary": "Mon like sur un commentaire",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du commentaire",
                        "name": "commentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/commentlike.CommentLike"
                        }
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Like non trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/comments/{id}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime un commentaire appartenant à l'utilisateur connecté",
                "tags": [
                    "Comments"
                ],
                "summary": "Supprimer un commentaire",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du commentaire",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Commentaire supprimé"
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Commentaire non trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour le contenu d'un commentaire appartenant à l'utilisateur connecté",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Modifier un commentaire",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du commentaire",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouveau contenu",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comment.CommentUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.Comment"
                        }
                    },
                    "400": {
                        "description": "Format invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Commentaire non trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/comments/{id}/replies": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne toutes les réponses d'un commentaire parent",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Réponses à un commentaire",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du commentaire parent",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/comment.Comment"
                            }
                        }
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/feed": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne les posts des comptes suivis par l'utilisateur connecté, paginés par curseur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Feed"
                ],
                "summary": "Fil d'actualité personnalisé",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Curseur de pagination",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre de résultats (défaut: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/post.PaginatedPostResponse"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notifications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's notifications in reverse chronological order with cursor-based pagination and an unread count",
                "tags": [
                    "Notifications"
                ],
                "summary": "List notifications",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pagination cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/notification.PaginatedNotificationResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/notifications/{id}/read": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Marks a single notification as read. Only the recipient can mark their own notification.",
                "tags": [
                    "Notifications"
                ],
                "summary": "Mark notification as read",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Notification ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "400": {
                        "description": "Invalid notification ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Notification not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/posts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne les posts paginés par curseur (cursor-based pagination)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Liste tous les posts (feed)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Curseur de pagination (opaque string)",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre de résultats (défaut: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/post.PaginatedPostResponse"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Crée un nouveau post avec au moins un média",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Créer un post",
                "parameters": [
                    {
                        "description": "Contenu et médias du post",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/post.PostCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/post.PostResponse"
                        }
                    },
                    "400": {
                        "description": "Format invalide ou aucun média",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Supprime un post appartenant à l'utilisateur connecté",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Supprimer un post",
                "parameters": [
                    {
                        "description": "ID du post à supprimer",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/post.PostDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Post supprimé"
                    },
                    "400": {
                        "description": "Format JSON invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Post introuvable",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Met à jour le contenu d'un post appartenant à l'utilisateur connecté",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Modifier un post",
                "parameters": [
                    {
                        "description": "Données de mise à jour",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/post.PostUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/post.Post"
                        }
                    },
                    "400": {
                        "description": "Format JSON invalide ou validation échouée",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Post introuvable ou non autorisé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/posts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne les posts d'un utilisateur précis, paginés par curseur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Posts d'un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de l'utilisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Curseur de pagination",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre de résultats (défaut: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/post.PaginatedPostResponse"
                        }
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/posts/{postID}/comments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne les commentaires racines d'un post, paginés par curseur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Commentaires d'un post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du post",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Curseur de pagination",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre de résultats (défaut: 10, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/comment.PaginatedCommentResponse"
                        }
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ajoute un commentaire (ou une réponse) sur un post. Passer parentCommentId pour une réponse.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Créer un commentaire",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du post",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Contenu du commentaire",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/comment.CommentCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/comment.Comment"
                        }
                    },
                    "400": {
                        "description": "Format invalide ou commentaire parent ne correspond pas au post",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Post ou commentaire parent non trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/posts/{postID}/likes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne tous les likes d'un post",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post Likes"
                ],
                "summary": "Likes d'un post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du post",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/like.Like"
                            }
                        }
                    },
                    "400": {
                        "description": "ID invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Ajoute une réaction (like/love/laugh) à un post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post Likes"
                ],
                "summary": "Liker un post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du post",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Type de réaction",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/like.LikeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/like.Like"
                        }
                    },
                    "400": {
                        "description": "Type de réaction invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Post non trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Déjà liké",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retire la réaction de l'utilisateur connecté sur un post",
                "tags": [
                    "Post Likes"
                ],
                "summary": "Supprimer un like sur un post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du post",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Like supprimé"
                    },
                    "400": {
                        "description": "ID invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Like non trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Change le type de réaction (like/love/laugh) de l'utilisateur connecté sur un post",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post Likes"
                ],
                "summary": "Modifier une réaction sur un post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du post",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Nouvelle réaction",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/like.LikeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/like.Like"
                        }
                    },
                    "400": {
                        "description": "ID ou type de réaction invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Like non trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/posts/{postID}/likes/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne le like de l'utilisateur connecté sur un post",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Post Likes"
                ],
                "summary": "Mon like sur un post",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID du post",
                        "name": "postID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/like.Like"
                        }
                    },
                    "400": {
                        "description": "ID invalide",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Like non trouvé",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/by-username/{username}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the public profile of a user by their username, including live followers, following, and posts counts.",
                "tags": [
                    "Users"
                ],
                "summary": "Get user by username",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Username",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{userID}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the public profile of a user by ID, including live followers, following, and posts counts.",
                "tags": [
                    "Users"
                ],
                "summary": "Get user profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID (UUID)",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/user.User"
                        }
                    },
                    "400": {
                        "description": "Invalid user ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{userID}/follow": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "L'utilisateur connecté commence à suivre un autre utilisateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Follow"
                ],
                "summary": "Suivre un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de l'utilisateur à suivre",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/follow.Follow"
                        }
                    },
                    "400": {
                        "description": "ID incorrect ou tentative de se suivre soi-même",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Déjà en train de suivre",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "L'utilisateur connecté arrête de suivre un autre utilisateur",
                "tags": [
                    "Follow"
                ],
                "summary": "Ne plus suivre un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de l'utilisateur à ne plus suivre",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Unfollow réussi"
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Relation de follow non trouvée",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{userID}/follow/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Vérifie si l'utilisateur connecté suit un autre utilisateur (pending/accepted)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Follow"
                ],
                "summary": "Statut de follow",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de l'utilisateur cible",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/follow.Follow"
                        }
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Relation non trouvée",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{userID}/followers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne la liste paginée des followers d'un utilisateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Follow"
                ],
                "summary": "Followers d'un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de l'utilisateur",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Numéro de page (défaut: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre de résultats (défaut: 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/users/{userID}/following": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retourne la liste paginée des utilisateurs que suit un utilisateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Follow"
                ],
                "summary": "Abonnements d'un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID de l'utilisateur",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Numéro de page (défaut: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre de résultats (défaut: 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "ID incorrect",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Erreur interne",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.LoginRequest": {
            "type": "object",
            "required": [
                "identifier",
                "password"
            ],
            "properties": {
                "identifier": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "auth.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "fullName",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "hugues@gmail.com"
                },
                "fullName": {
                    "type": "string",
                    "example": "Goli yao Hugues"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "pass1234"
                },
                "username": {
                    "type": "string",
                    "minLength": 3,
                    "example": "huguesgoli"
                }
            }
        },
        "comment.Comment": {
            "type": "object",
            "properties": {
                "commentId": {
                    "type": "string"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "likesCount": {
                    "type": "integer"
                },
                "parentCommentId": {
                    "type": "string"
                },
                "postId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "comment.CommentCreateRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 2000
                },
                "parentCommentId": {
                    "type": "string"
                }
            }
        },
        "comment.CommentUpdateRequest": {
            "type": "object",
            "required": [
                "content"
            ],
            "properties": {
                "content": {
                    "type": "string",
                    "maxLength": 2000
                }
            }
        },
        "comment.PaginatedCommentResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/comment.Comment"
                    }
                },
                "hasMore": {
                    "type": "boolean"
                },
                "nextCursor": {
                    "type": "string"
                }
            }
        },
        "commentlike.CommentLike": {
            "type": "object",
            "properties": {
                "commentId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "reactionType": {
                    "$ref": "#/definitions/like.ReactionType"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "commentlike.reactionRequest": {
            "type": "object",
            "required": [
                "reactionType"
            ],
            "properties": {
                "reactionType": {
                    "$ref": "#/definitions/like.ReactionType"
                }
            }
        },
        "follow.Follow": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "followeeId": {
                    "type": "string"
                },
                "followerId": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/follow.FollowStatus"
                }
            }
        },
        "follow.FollowStatus": {
            "type": "string",
            "enum": [
                "pending",
                "accepted"
            ],
            "x-enum-varnames": [
                "StatusPending",
                "StatusAccepted"
            ]
        },
        "like.Like": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "postID": {
                    "type": "string"
                },
                "reactionType": {
                    "$ref": "#/definitions/like.ReactionType"
                },
                "updated_at": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                }
            }
        },
        "like.LikeRequest": {
            "type": "object",
            "required": [
                "reactionType"
            ],
            "properties": {
                "reactionType": {
                    "$ref": "#/definitions/like.ReactionType"
                }
            }
        },
        "like.ReactionType": {
            "type": "string",
            "enum": [
                "like",
                "love",
                "laugh"
            ],
            "x-enum-varnames": [
                "ReactionLike",
                "ReactionLove",
                "ReactionLaugh"
            ]
        },
        "notification.Notification": {
            "type": "object",
            "properties": {
                "actorId": {
                    "type": "string"
                },
                "actorUsername": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "entityId": {
                    "type": "string"
                },
                "notificationId": {
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "recipientId": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/notification.NotificationType"
                }
            }
        },
        "notification.NotificationType": {
            "type": "string",
            "enum": [
                "like_post",
                "comment_post",
                "like_comment",
                "new_follower"
            ],
            "x-enum-varnames": [
                "TypeLikePost",
                "TypeCommentPost",
                "TypeLikeComment",
                "TypeNewFollower"
            ]
        },
        "notification.PaginatedNotificationResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/notification.Notification"
                    }
                },
                "hasMore": {
                    "type": "boolean"
                },
                "nextCursor": {
                    "type": "string"
                },
                "unreadCount": {
                    "type": "integer"
                }
            }
        },
        "post.PaginatedPostResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/post.PostResponse"
                    }
                },
                "has_more": {
                    "type": "boolean"
                },
                "next_cursor": {
                    "type": "string"
                }
            }
        },
        "post.Post": {
            "type": "object",
            "properties": {
                "commentsCount": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "likesCount": {
                    "type": "integer"
                },
                "postID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "post.PostCreateRequest": {
            "type": "object",
            "required": [
                "content",
                "medias"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "medias": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/postmedia.PostMedia"
                    }
                }
            }
        },
        "post.PostDeleteRequest": {
            "type": "object",
            "required": [
                "postID"
            ],
            "properties": {
                "postID": {
                    "type": "string"
                }
            }
        },
        "post.PostResponse": {
            "type": "object",
            "properties": {
                "commentsCount": {
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "likesCount": {
                    "type": "integer"
                },
                "media": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/postmedia.PostMedia"
                    }
                },
                "postID": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "post.PostUpdateRequest": {
            "type": "object",
            "required": [
                "content",
                "postID"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "postID": {
                    "type": "string"
                }
            }
        },
        "postmedia.PostMedia": {
            "type": "object",
            "required": [
                "type",
                "url"
            ],
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "mediaID": {
                    "type": "string"
                },
                "postID": {
                    "type": "string"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "image",
                        "video"
                    ]
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "user.User": {
            "type": "object",
            "properties": {
                "bio": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "followersCount": {
                    "type": "integer"
                },
                "followingCount": {
                    "type": "integer"
                },
                "fullName": {
                    "type": "string"
                },
                "postsCount": {
                    "type": "integer"
                },
                "profilePicURL": {
                    "type": "string"
                },
                "userID": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Entrez le token JWT avec le préfixe \"Bearer \". Exemple: \"Bearer eyJhbGci...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Insta-Lite API",
	Description:      "API REST pour une application de type Instagram (posts, likes, commentaires, follow).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
